package fr.unicaen.iutcaen.model.entities;

import fr.unicaen.iutcaen.config.Config;
import fr.unicaen.iutcaen.model.Point;
import javafx.beans.property.SimpleDoubleProperty;
import javafx.scene.paint.Color;



public abstract class Entity {
    protected int id;
    protected Point position;
    protected SimpleDoubleProperty mass = new SimpleDoubleProperty();

    protected Color color;

    /**
     * An entity is anything that may appear on screen
     * For example there will be Pellet Cells and Virus
     * They compose the game and the player
     * An entity may be displayed on the screen and can
     * be eaten and make other entities react
     * @param id The Id of the entity. Most of the time it will be generated by the IdDistributor
     * @param position The position of the entity on the map
     * @param mass The mass of the entity that will define its size most of the time
     * @param color The Color of the entity when it will be displayed on screen
     */
    public Entity(int id, Point position, double mass, Color color) {
        this.id = id;
        this.position = position;
        this.mass.set(mass);
        this.color = color;
    }

    public abstract void update(); // updates the state of the entity

    // Getters et setters
    public int getId() { return id; }
    public Point getPosition() { return position; }
    public double getMass() { return mass.getValue(); }
    public void setPosition(Point position) { this.position = position; }
    public void setMass(double mass) { this.mass.set(mass); }

    public Color getColor() {
        return color;
    }

    public void setColor(Color color) {
        this.color = color;
    }

    public SimpleDoubleProperty getMassProperty(){
        return mass;
    }

    public double getSize(){
        return Config.SIZE_RATIO *Math.sqrt(this.getMass());
    }
}
